#!/usr/bin/env sh

bspc monitor -d 0 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap           8
bspc config top_padding          32

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modified      mod4
bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr &

~/.config/polybar/launch.sh
